### ISSUE TITLE
  File "/media/sc1/BED0CCE0D0CCA04F/lizhipeng/BIS/SVIN/interpolation/motion_model.py", line 4, in <module>     from grid import Dense3DSpatialTransformer ImportError: No module named grid

### ISSUE THREAD

**Issue by wcoool** [guoyu-niubility/SVIN#2]
File "/media/sc1/BED0CCE0D0CCA04F/lizhipeng/BIS/SVIN/interpolation/motion_model.py", line 4, in <module>
    from grid import Dense3DSpatialTransformer
ImportError: No module named grid

**Comment by yyguo0536** [comment]
Updated.
