### ISSUE TITLE
Some question about the idea

### ISSUE THREAD

**Issue by ChenWWWeixiang** [guoyu-niubility/SVIN#3]
Thanks for sharing your research, which inspire me a lot! 
There are still some question on the framework after reading your paper and checking the code. It will be very pleasure if you can help me better understanding it.
1. In my opinion, the interpolation part of the network is a fine-tuning of deformation field output by the first part. Why don't we derectly output the target interpolated results in the interpolation part?
2.  Can Eq5 and 6 help in the experiments?

**Comment by yyguo0536** [comment]
Thanks for your interest in my work. Please see the following:
-1. You are right. The interpolation part can be treated as a refinement network. However, the biological motion (i.e., cardiac motion) usually not linear, we expect our interpolated time-point volume to follow the real motion pace. Then, we can leverage the interpolation network to derive the velocity field of cardiac motion in the cardiac cycle from the motion field between ED and ES. Thus, it's a motion-guide interpolation problem, and we need to obtain the motion field firstly. Actually, we would like to build an interpolation network that can extract the biological motion in common space (it's like a 4D atlas). 
-2. Eq 5 and Eq6 are used to obtain a rough linear interpolation volume, which provides the bi-directional information. This is inspired by the video interpolation problem. For example, there are two images I0, I1 showing the football moving. We would like to interpolate an image It between I0 and I1. But there are some backgrounds obscured by the football in I0 while I1 can provide the backgrounds lost in I0. Thus, we consider the bi-directional motion can provide more information.
