### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by cyiheng** [guoyu-niubility/SVIN#6]
Hi !

I have an issue about the memory and I remember that you said in your paper that you trained on two 11GB 1080Ti GPU.
``` 
RuntimeError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 10.92 GiB total capacity; 10.18 GiB already allocated; 73.38 MiB free; 10.27 GiB reserved in total by PyTorch)
```
I was hoping if you can tell me what did you change in your code (or maybe just an option that I missed) to work on both GPU to avoid this memory issue.

Thanks in advance !

**Comment by yyguo0536** [comment]
For me, I firstly defined two devices like:
"device0 = torch.device('cuda:0')
device1 = torch.device('cuda:1')"
And then you can set the motion model to device0 and interpolation model to device1.
